/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/base/Avatar.vue')['default']
    Badge: typeof import('./components/base/Badge.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    Card: typeof import('./components/base/Card.vue')['default']
    Dropdown: typeof import('./components/base/Dropdown.vue')['default']
    DropdownItem: typeof import('./components/base/DropdownItem.vue')['default']
    Empty: typeof import('./components/base/Empty.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/base/Input.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    Modal: typeof import('./components/base/Modal.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/base/Tabs.vue')['default']
  }
}
